# Ask user to enter their name
print("What is your name?")
name = input()
print(f"It is nice to meet you {name}")
print("Please enter a character for the eye")
eye = input()
print("The robots expression is now as follows:")
print("##########")
print(f"#  {eye}  {eye}  #")
print("#  ----  #")
print("##########")
print("What is your name?")
name2 = input()
print("How old are you (in years)?")
age = input()
print("How tall are you (in meters)?")
height = float(input())
print("How much do you weigh (in kilograms)?")
weight = int(input())
bmi = weight/(height*height)
print(f"{name2} you are {age} years old and your bmi is {bmi}")
print()
print("Please enter the number of lives.")
lives = int(input())
print("Please enter the energy level.")
energy = int(input())
print("Please enter the shield level.")
shield = int(input())
print(f"Lives: {'♥'*lives}")
print(f"Energy: {'♦'*energy}")
print(f"Shield:{'♦'*shield}")
print("Health has been set.")